#spring.application.name=casp-modulith
spring:
  application:
    name: casp-modulith
  data:
    mongodb:
      database: caspdb
      uri: ${mongodb.container.port}
      uuid-representation: standard
