spring:
  application:
    name: admin-v2
  jackson:
    time-zone: UTC

casp:
  europenet-api-endpoint: https://europetnet.ehealth.gv.at/Index.aspx?mn={chipNumber}
  cron: 0 0 0 * * *
  internal-exception-response: "An internal error has occurred"
